backend:
  name: github
  repo: oisif-studio/oisif-studio.github.io
  branch: master

publish_mode: editorial_workflow

media_folder: "images"

collections:
  - name: "articles"
    label: "article"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - label: "Settings"
    name: "settings"
    delete: false
    files:
      - label: "Team"
        name: "team"
        file: "_data/team.yml"
        widget: list
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Role", name: "role", widget: "string"}
          - {label: "Photo", name: "photo", widget: "image"}
          - {label: "Website", name: "website", widget: "string"}