backend:
  name: github
  repo: oisif-studio/oisif-studio.github.io
  branch: master

publish_mode: editorial_workflow

media_folder: "images"

collections:
  - name: "articles"
    label: "article"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - name: "authors"
    label: "Authors"
    file: "_data/authors.yml"
    description: "Author descriptions"
    fields:
      - name: authors
        label: Authors
        label_singular: "Author"
        widget: list
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Role", name: "role", widget: "string"}
          - {label: "Website", name: "website", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}