backend:
  name: "github"
  repo: "oisif-studio/oisif-studio.github.io"
  branch: "master"

publish_mode: "editorial_workflow"

media_folder: "images"

collections:
  - label: "Articles"
    name: "article"
    folder: "_posts/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "article"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - label: "Projects"
    name: "project"
    folder: "_posts/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "project"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - label: "Resources"
    name: "resources"
    folder: "_posts/resources"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "resource"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "resource"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        fields:
          - {label: "Tag", name: "tag", widget: "string"}
      - label: "Resource"
        name: "resource"
        widget: "list"
        fields:
          - {label: "Url Name", name: "name", widget: "string"}
          - {label: "Url Link", name: "link", widget: "string"}

  # - label: "Team"
  #   name: "team"
  #   file: "_data/team.yml"
  #   fields:
  #     - label: "test"
  #       widget: "object"
  #       fields:
  #         - {label: "Avatar", name: "avatar", widget: "image"}
  #         - {label: "Name", name: "name", widget: "string"}
  #         - {label: "Position", name: "position", widget: "string"}


  - label: "Settings"
    name: "settings"
    files:
      - label: "Tags"
        name: "tags"
        file: "_data/tags-list.yml"
        fields:
          - label: "Tags"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
      - label: "Team"
        name: "team"
        file: "_data/authors-list.yml"
        fields:
          - label: "Pseudos"
            widget: "list"
            fields:
              - {label: "Pseudo", name: "name", widget: "string"}
          # - label: "People"
          #   name: "people"
          #   widget: "list"
          #   fields:
          #   - {label: "Pseudo", name: "pseudo", widget: "string"}
          #   - label: "data"
          #     name: "data"
          #     widget: "object"
          #     fields:
          #       - {label: "Avatar", name: "avatar", widget: "image"}
          #       - {label: "Name", name: "name", widget: "string"}
          #       - {label: "Position", name: "position", widget: "string"}
          #       - {label: "Website", name: "web", widget: "string"}