backend:
  name: "github"
  repo: "oisif-studio/oisif-studio.github.io"
  branch: "master"

publish_mode: "editorial_workflow"

media_folder: "images"

collections:
  - label: "Articles"
    name: "article"
    folder: "_posts/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Category", name: "category", widget: "hidden", default: "article"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - label: "Settings"
    name: "settings"
    files:
      - label: "Team"
        name: "team"
        file: "_data/team.yml"
        fields:
          - label: "Persons"
            name: "person"
            widget: "list"
            fields:
              - {label: "Photo", name: "photo", widget: "image"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Website", name: "website", widget: "string"}